<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ankit" failures="0" tests="3" name="readDataFromDataProvider.ReadDataFromSameClass" time="59.541" errors="2" timestamp="2024-08-06T23:42:58 IST" skipped="0">
  <testcase classname="readDataFromDataProvider.ReadDataFromSameClass" name="Login" time="20.097">
    <error message="Method readDataFromDataProvider.ReadDataFromSameClass.Login() didn&#039;t finish within the time-out 20000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method readDataFromDataProvider.ReadDataFromSameClass.Login() didn't finish within the time-out 20000
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:347)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- Login -->
  <system-out/>
  <testcase classname="readDataFromDataProvider.ReadDataFromSameClass" name="Login" time="20.148">
    <error message="Method readDataFromDataProvider.ReadDataFromSameClass.Login() didn&#039;t finish within the time-out 20000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method readDataFromDataProvider.ReadDataFromSameClass.Login() didn't finish within the time-out 20000
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:347)
at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- Login -->
  <system-out/>
  <testcase classname="readDataFromDataProvider.ReadDataFromSameClass" name="Login" time="19.296"/>
  <system-out/>
</testsuite> <!-- readDataFromDataProvider.ReadDataFromSameClass -->
